###
GET http://localhost:5000/api/products
###

GET http://localhost:5000/api/products/5f5c8cfee094f621ac315d71


###
POST http://localhost:5000/api/users/signin
Content-Type: application/json

{
    "email" : "daginegussu@gmail.com",
    "password" : "daginegussu"
}

###

POST http://localhost:5000/api/users/signin
Content-Type: application/json

{
    "email" : "abunegussu@gmail.com",
    "password" : "abunegussu"
}

###
POST http://localhost:5000/api/users/signup
Content-Type: application/json

{
    "email" : "abunegussu@gmail.com",
    "password" : "abunegussu",
    "name": "Abu Negussu"
}

###
POST http://localhost:5000/api/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjViOGI5NDg1OWFmNTJiNjA1NWE0NWIiLCJuYW1lIjoiRGFnbWF3aSBOZWd1c3N1IiwiZW1haWwiOiJkYWdpbmVndXNzdUBnbWFpbC5jb20iLCJ0eXBlIjoiYWRtaW4iLCJpYXQiOjE1OTk4OTk0OTgsImV4cCI6MTYwMDA3MjI5OH0.xdsv24E2Ijw45-3lF8_SnpkuinI_JGz-5on-dnLRWyk

{
			"name": "Classic BBBB Shirt",
			"images": [
				"/images/nike/black2.png",
				"/images/nike/black3.png",
				"/images/nike/black4.png",
				"/images/nike/black1.png"
			],
			"category": "shirts",
			"price": 42,
			"brand": "Nike",
			"rating": 4.5,
			"reviewNo": 9,
			"description": "this is description",
			"stock": 12
		}

###
DELETE  http://localhost:5000/api/products/5f5ca87b13bb2934e80c14b2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjViOGI5NDg1OWFmNTJiNjA1NWE0NWIiLCJuYW1lIjoiRGFnbWF3aSBOZWd1c3N1IiwiZW1haWwiOiJkYWdpbmVndXNzdUBnbWFpbC5jb20iLCJ0eXBlIjoiYWRtaW4iLCJpYXQiOjE1OTk4OTk0OTgsImV4cCI6MTYwMDA3MjI5OH0.xdsv24E2Ijw45-3lF8_SnpkuinI_JGz-5on-dnLRWyk


###
PUT http://localhost:5000/api/orders/5f5e63e599cbfc1730dd87e9/pay/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjViOGU1NDg5MTI4NjFhNzA3NzZiNmUiLCJuYW1lIjoiQWJ1IE5lZ3Vzc3UiLCJlbWFpbCI6ImFidW5lZ3Vzc3VAZ21haWwuY29tIiwidHlwZSI6InVzZXIiLCJpYXQiOjE2MDAwMjIyNjgsImV4cCI6MTYwMDE5NTA2OH0.gVVeH4lgi_0ST9NYVLx1pLkAieyiHKYf3guZeelCIlk

